// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ischzrefshzeuxyrglyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzY2h6cmVmc2h6ZXV4eXJnbHloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTMzMTgsImV4cCI6MjA2OTQ2OTMxOH0.89d5F6AQPvTirjJzhtPykETes_Dm9sgn9_P8BT6BbVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});